import os
import logging
import certifi
import urllib3
import requests
import smtplib
import markdown
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import TypedDict, List, Optional
from datetime import datetime

# Force disable SSL warnings and verification for restricted environments
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
old_merge_environment_settings = requests.Session.merge_environment_settings

def merge_environment_settings(self, url, proxies, stream, verify, cert):
    settings = old_merge_environment_settings(self, url, proxies, stream, verify, cert)
    settings['verify'] = False
    return settings

requests.Session.merge_environment_settings = merge_environment_settings

# Configure SSL for Windows
os.environ['SSL_CERT_FILE'] = certifi.where()
os.environ['REQUESTS_CA_BUNDLE'] = certifi.where()
os.environ['CURL_CA_BUNDLE'] = "" # Disable for curl-based tools if any

from dotenv import load_dotenv
from tavily import TavilyClient
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import StateGraph, END

# Setup Logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Load environment variables
load_dotenv()

# State Definition
class AgentState(TypedDict):
    query: str
    raw_news: List[dict]
    summary: str
    email_content: str
    email_status: bool

# Initialize Clients
tavily = TavilyClient(api_key=os.environ["TAVILY_API_KEY"])
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", google_api_key=os.environ["GOOGLE_API_KEY"])

# Nodes
def research_node(state: AgentState):
    """Search for news using Tavily."""
    logger.info("Starting Research Node...")
    search_queries = [
        "The Wonderful Company news April 2026",
        "Wonderful Pistachios news April 2026",
        "FIJI Water news April 2026"
    ]
    
    all_results = []
    for query in search_queries:
        response = tavily.search(
            query=query,
            search_depth="advanced",
            exclude_domains=["wikipedia.org", "facebook.com", "twitter.com", "instagram.com", "linkedin.com"]
        )
        all_results.extend(response.get('results', []))
    
    return {"raw_news": all_results}

def analyst_node(state: AgentState):
    """Analyze news using Gemini-2.5-flash."""
    logger.info("Starting Analyst Node...")
    news_context = "\n".join([f"- {r['title']}: {r['content']}" for r in state['raw_news']])
    
    prompt = f"""
    Analyze the following news results for The Wonderful Company from April 2026.
    
    Key milestones to look for:
    1. The company's climb to #72 on Fortune’s 100 Best Companies list.
    2. Sweet Cinnamon Pistachios re-release.
    3. Lewis Cellars' Medallion Reserve launch.
    
    News Data:
    {news_context}
    
    Provide a concise summary focusing on these key points and any other significant business updates.
    """
    
    response = llm.invoke(prompt)
    return {"summary": response.content}

def email_node(state: AgentState):
    """Format news into a Markdown and HTML email and send it via SMTP."""
    logger.info("Starting Email Node...")
    
    date_str = datetime.now().strftime("%B %d, %Y")
    subject = f"Daily News Briefing: The Wonderful Company - {date_str}"
    
    # Generate Markdown
    email_markdown = f"""
# Daily News Briefing: The Wonderful Company
**Date:** {date_str}

{state['summary']}

---
*This is an automated briefing generated by the LangGraph News Agent.*
    """
    
    # Convert to HTML
    email_html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
            h2 {{ color: #2980b9; margin-top: 20px; }}
            .footer {{ font-style: italic; color: #777; margin-top: 30px; border-top: 1px solid #eee; padding-top: 10px; }}
        </style>
    </head>
    <body>
        {markdown.markdown(email_markdown)}
    </body>
    </html>
    """
    
    def send_email(text_content: str, html_content: str):
        sender_email = os.getenv("EMAIL_SENDER")
        receiver_email = os.getenv("EMAIL_RECEIVER")
        password = os.getenv("EMAIL_PASSWORD")
        smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
        smtp_port = int(os.getenv("SMTP_PORT", "465"))

        if not all([sender_email, receiver_email, password]):
            logger.error("Missing email configuration (EMAIL_SENDER, EMAIL_RECEIVER, or EMAIL_PASSWORD).")
            return False

        msg = MIMEMultipart("alternative")
        msg["From"] = sender_email
        msg["To"] = receiver_email
        msg["Subject"] = subject
        
        # Attach both parts (client will choose the best one, usually HTML)
        msg.attach(MIMEText(text_content, "plain"))
        msg.attach(MIMEText(html_content, "html"))

        try:
            logger.info(f"Sending email via {smtp_server}:{smtp_port}...")
            if smtp_port == 465:
                with smtplib.SMTP_SSL(smtp_server, smtp_port) as server:
                    server.login(sender_email, password)
                    server.send_message(msg)
            else:
                with smtplib.SMTP(smtp_server, smtp_port) as server:
                    server.starttls()
                    server.login(sender_email, password)
                    server.send_message(msg)
            logger.info("Email sent successfully!")
            return True
        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            return False

    status = send_email(email_markdown, email_html)
    
    return {"email_content": email_markdown, "email_status": status}

# Graph Construction
def build_graph():
    workflow = StateGraph(AgentState)
    
    workflow.add_node("research", research_node)
    workflow.add_node("analyst", analyst_node)
    workflow.add_node("email", email_node)
    
    workflow.set_entry_point("research")
    workflow.add_edge("research", "analyst")
    workflow.add_edge("analyst", "email")
    workflow.add_edge("email", END)
    
    return workflow.compile()

if __name__ == "__main__":
    logger.info("Initializing LangGraph News Agent...")
    app = build_graph()
    
    initial_state = {
        "query": "The Wonderful Company Daily Briefing",
        "raw_news": [],
        "summary": "",
        "email_content": "",
        "email_status": False
    }
    
    final_output = app.invoke(initial_state)
    
    print("\n--- Final Email Content ---")
    print(final_output["email_content"])
    print(f"\nEmail Send Status: {final_output['email_status']}")
