import os
import logging
import smtplib
import markdown
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import TypedDict, List, Optional
from datetime import datetime

from dotenv import load_dotenv
from tavily import TavilyClient
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import StateGraph, END

# Setup Logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Load environment variables
load_dotenv()

# Configuration and API Keys
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
EMAIL_SENDER = os.getenv("EMAIL_SENDER")
EMAIL_RECEIVER = os.getenv("EMAIL_RECEIVER")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "465"))

# State Definition
class AgentState(TypedDict):
    query: str
    raw_news: List[dict]
    summary: str
    email_content: str
    email_status: bool

# Initialize Clients
tavily = TavilyClient(api_key=TAVILY_API_KEY)
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", google_api_key=GOOGLE_API_KEY)

# Nodes
def research_node(state: AgentState):
    """Search for news using Tavily."""
    logger.info("Starting Research Node...")
    search_queries = [
        "The Wonderful Company news past week",
        "Wonderful Pistachios news past week",
        "FIJI Water news past week"
    ]
    
    all_results = []
    for query in search_queries:
        response = tavily.search(
            query=query,
            search_depth="advanced",
            time_range="week",
            exclude_domains=["wikipedia.org", "facebook.com", "twitter.com", "instagram.com", "linkedin.com"]
        )
        all_results.extend(response.get('results', []))
    
    return {"raw_news": all_results}

def analyst_node(state: AgentState):
    """Analyze news using Gemini-2.5-flash."""
    logger.info("Starting Analyst Node...")
    news_context = "\n".join([f"- {r['title']} ({r['url']}): {r['content']}" for r in state['raw_news']])
    
    prompt = f"""
    Analyze the following news results for The Wonderful Company and its associated brands (such as Wonderful Pistachios, FIJI Water, POM Wonderful, etc.) from the past week.
    
    News Data:
    {news_context}
    
    Provide a concise summary for a Weekly News Briefing. Focus on significant business updates, product news, community initiatives, or any other relevant information pertaining to The Wonderful Company.
    
    IMPORTANT: For each major point or news item in your summary, include the corresponding source link(s) from the provided News Data.
    
    If no significant news is found in the data provided, please provide a brief, professional statement indicating that there were no major updates this week.
    """
    
    response = llm.invoke(prompt)
    return {"summary": response.content}

def email_node(state: AgentState):
    """Format news into a Markdown and HTML email and send it via SMTP."""
    logger.info("Starting Email Node...")
    
    date_str = datetime.now().strftime("%B %d, %Y")
    subject = f"Weekly News Briefing: The Wonderful Company - {date_str}"
    
    # Generate Markdown
    email_markdown = f"""
# Weekly News Briefing: The Wonderful Company
**Date:** {date_str}

{state['summary']}

---
*This is an automated briefing generated by the LangGraph News Agent.*
    """
    
    # Convert to HTML
    email_html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
            h2 {{ color: #2980b9; margin-top: 20px; }}
            .footer {{ font-style: italic; color: #777; margin-top: 30px; border-top: 1px solid #eee; padding-top: 10px; }}
        </style>
    </head>
    <body>
        {markdown.markdown(email_markdown)}
    </body>
    </html>
    """
    
    def send_email(text_content: str, html_content: str):
        if not all([EMAIL_SENDER, EMAIL_RECEIVER, EMAIL_PASSWORD]):
            logger.error("Missing email configuration (EMAIL_SENDER, EMAIL_RECEIVER, or EMAIL_PASSWORD).")
            return False

        msg = MIMEMultipart("alternative")
        msg["From"] = EMAIL_SENDER
        msg["To"] = EMAIL_RECEIVER
        msg["Subject"] = subject
        
        # Attach both parts (client will choose the best one, usually HTML)
        msg.attach(MIMEText(text_content, "plain"))
        msg.attach(MIMEText(html_content, "html"))

        try:
            logger.info(f"Sending email via {SMTP_SERVER}:{SMTP_PORT}...")
            if SMTP_PORT == 465:
                with smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT) as server:
                    server.login(EMAIL_SENDER, EMAIL_PASSWORD)
                    server.send_message(msg)
            else:
                with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
                    server.starttls()
                    server.login(EMAIL_SENDER, EMAIL_PASSWORD)
                    server.send_message(msg)
            logger.info("Email sent successfully!")
            return True
        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            return False

    status = send_email(email_markdown, email_html)
    
    return {"email_content": email_markdown, "email_status": status}

# Graph Construction
def build_graph():
    workflow = StateGraph(AgentState)
    
    workflow.add_node("research", research_node)
    workflow.add_node("analyst", analyst_node)
    workflow.add_node("email", email_node)
    
    workflow.set_entry_point("research")
    workflow.add_edge("research", "analyst")
    workflow.add_edge("analyst", "email")
    workflow.add_edge("email", END)
    
    return workflow.compile()

if __name__ == "__main__":
    logger.info("Initializing LangGraph News Agent...")
    app = build_graph()
    
    initial_state = {
        "query": "The Wonderful Company Weekly Briefing",
        "raw_news": [],
        "summary": "",
        "email_content": "",
        "email_status": False
    }
    
    final_output = app.invoke(initial_state)
    
    print("\n--- Final Email Content ---")
    print(final_output["email_content"])
    print(f"\nEmail Send Status: {final_output['email_status']}")
